name: CI

on:
  push:
    branches: [ guest_accounts ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZ_USERNAME: ${{ secrets.AZ_USERNAME }}
      AZ_TOKEN: ${{ secrets.AZ_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
    - uses: actions/checkout@v4
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "${{ secrets.AZ_USERNAME  }}" --password "${{ secrets.AZ_TOKEN }}" repocr.azurecr.io
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --use-inline-cache --push +build
