name: Prod push

on:
  schedule:
    # - cron: '0 0 * * 0' #weekly run
    - cron: '0 * * * *' #hourly test
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_SECRETS: "GUEST_TOKENS_TOKEN=${{ secrets.GUEST_TOKENS_TOKEN }}"
    steps:
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.8
    - uses: actions/checkout@v4
      with:
        ref: 'guest_accounts'
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: echo ${{ secrets.REPO_PASSWORD }} | docker login --username ${{ secrets.REPO_USERNAME  }} --password-stdin repo.nohost.network
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --secret GUEST_TOKENS_TOKEN=${{ secrets.GUEST_TOKENS_TOKEN }} --ci --push --remote-cache repo.nohost.network/nitter:cache +prod-push
